### ISSUE TITLE
Regression in 0.4.4

### ISSUE THREAD

**Issue by feuerste** [jeromefroe/lru-rs#78]
Hi, I just wanted to update to `0.4.4`, but realized that it introduced a severe issue, most probably due to #74. With this simple test program you can reproduce it (I tested it on a Mac):

```
cargo init lru_regression
cd lru_regression
```

`src/main.rs`:
```rust
fn main() -> std::io::Result<()> {
    loop {
        lru::LruCache::new(1).put(0, std::fs::File::open("Cargo.toml")?);
    }
}
```

`Cargo.toml`:
```toml
[package]
name = "lru_regression"
version = "0.1.0"
edition = "2018"

[dependencies]
lru = "=0.4.4"
```

```
cargo build --release
target/release/lru_regression
```

With `lru = "=0.4.3"` the program will basically run forever, with `lru = "=0.4.4"` you will run into `Error: Os { code: 24, kind: Other, message: "Too many open files" }` pretty soon. So it seems there is an issue in the new dropping code.
